class Country {
  int id;
  String code;
  String name;
 
  Country(this.code, this.name);
 
  static List<Country> getCountries() {
    return <Country>[
      Country("AF", 'Afghanistan'),
      Country("AL", 'Albania'),
      Country("DZ", 'Algeria'),
      Country("AO", 'Angola'),
      Country("AM", 'Armenia'),
      Country("AU", 'Australia'),
      Country("AT", 'Austria'),
      Country("AZ", 'Azerbaijan'),
      Country("BS", 'Bahamas'),
      Country("BD", 'Bangladesh'),
      Country("BY", 'Belarus'),
      Country("BE", 'Belgium'),
      Country("BZ", 'Belize'),
      Country("BJ", 'Benin'),
      Country("BT", 'Bhutan'),
      Country("BO", 'Bolivia'),
      Country("BA", 'Bosnia'),
      Country("BW", 'Botswana'),
      Country("BR", 'Brazil'),
      Country("BN", 'Brunei Darussalam'),
      Country("BG", 'Bulgaria'),
      Country("BF", 'Burkina Faso'),
      Country("BI", 'Burundi'),
      Country("KH", 'Cambodia'),
      Country("CM", 'Cameroon'),
      Country("CA", 'Canada'),
      Country("CI", 'Ivory Coast'),
      Country("CF", 'Central African Republic'),
      Country("TD", 'Chad'),
      Country("CL", 'Chile'),
      Country("CN", 'China'),
      Country("CO", 'Colombia'),
      Country("CG", 'Congo'),
      Country("CD", 'Democratic Republic of Congo'),
      Country("CR", 'Costa Rica'),
      Country("HR", 'Croatia'),
      Country("CU", 'Cuba'),
      Country("CY", 'Cyprus'),
      Country("CZ", 'Czech Republic'),
      Country("DK", 'Denmark'),
      Country("DP", 'Diamond Princess'),
      Country("DJ", 'Djibouti'),
      Country("DO", 'Dominican Republic'),
      Country("CD", 'DR Congo'),
      Country("EC", 'Ecuador'),
      Country("EG", 'Egypt'),
      Country("SV", 'El Salvador'),
      Country("GQ", 'Equatorial Guinea'),
      Country("ER", 'Eritrea'),
      Country("EE", 'Estonia'),
      Country("ET", 'Ethiopia'),
      Country("FK", 'Falkland Islands'),
      Country("FJ", 'Fiji'),
      Country("FI", 'Finland'),
      Country("FR", 'France'),
      Country("GF", 'French Guiana'),
      Country("TF", 'French Southern Territories'),
      Country("GA", 'Gabon'),
      Country("GM", 'Gambia'),
      Country("GE", 'Georgia'),
      Country("DE", 'Germany'),
      Country("GH", 'Ghana'),
      Country("GR", 'Greece'),
      Country("GL", 'Greenland'),
      Country("GT", 'Guatemala'),
      Country("GN", 'Guinea'),
      Country("GW", 'Guinea-Bissau'),
      Country("GY", 'Guyana'),
      Country("HT", 'Haiti'),
      Country("HN", 'Honduras'),
      Country("HK", 'Hong Kong'),
      Country("HU", 'Hungary'),
      Country("IS", 'Iceland'),
      Country("IN", 'India'),
      Country("ID", 'Indonesia'),
      Country("IR", 'Iran'),
      Country("IQ", 'Iraq'),
      Country("IE", 'Ireland'),
      Country("IL", 'Israel'),
      Country("IT", 'Italy'),
      Country("JM", 'Jamaica'),
      Country("JP", 'Japan'),
      Country("JO", 'Jordan'),
      Country("KZ", 'Kazakhstan'),
      Country("KE", 'Kenya'),
      Country("KP", 'Korea'),
      Country("XK", 'Kosovo'),
      Country("KW", 'Kuwait'),
      Country("KG", 'Kyrgyzstan'),
      Country("LA", 'Lao'),
      Country("LV", 'Latvia'),
      Country("LB", 'Lebanon'),
      Country("LS", 'Lesotho'),
      Country("LR", 'Liberia'),
      Country("LY", 'Libya'),
      Country("LT", 'Lithuania'),
      Country("LU", 'Luxembourg'),
      Country("MK", 'Macedonia'),
      Country("MG", 'Madagascar'),
      Country("MW", 'Malawi'),
      Country("MY", 'Malaysia'),
      Country("ML", 'Mali'),
      Country("MR", 'Mauritania'),
      Country("MX", 'Mexico'),
      Country("MD", 'Moldova'),
      Country("MN", 'Mongolia'),
      Country("ME", 'Montenegro'),
      Country("MA", 'Morocco'),
      Country("MZ", 'Mozambique'),
      Country("MM", 'Myanmar'),
      Country("NA", 'Namibia'),
      Country("NP", 'Nepal'),
      Country("NL", 'Netherlands'),
      Country("NC", 'New Caledonia'),
      Country("NZ", 'New Zealand'),
      Country("NI", 'Nicaragua'),
      Country("NE", 'Niger'),
      Country("NG", 'Nigeria'),
      Country("KP", 'North Korea'),
      Country("NO", 'Norway'),
      Country("OM", 'Oman'),
      Country("PK", 'Pakistan'),
      Country("PS", 'Palestine'),
      Country("PA", 'Panama'),
      Country("PG", 'Papua New Guinea'),
      Country("PY", 'Paraguay'),
      Country("PE", 'Peru'),
      Country("PH", 'Philippines'),
      Country("PL", 'Poland'),
      Country("PT", 'Portugal'),
      Country("PR", 'Puerto Rico'),
      Country("QA", 'Qatar'),
      Country("XK", 'Republic of Kosovo'),
      Country("RO", 'Romania'),
      Country("RU", 'Russia'),
      Country("RW", 'Rwanda'),
      Country("SA", 'Saudi Arabia'),
      Country("SN", 'Senegal'),
      Country("RS", 'Serbia'),
      Country("SL", 'Sierra Leone'),
      Country("SG", 'Singapore'),
      Country("SK", 'Slovakia'),
      Country("SI", 'Slovenia'),
      Country("SB", 'Solomon Islands'),
      Country("SO", 'Somalia'),
      Country("ZA", 'South Africa'),
      Country("KR", 'South Korea'),
      Country("SS", 'South Sudan'),
      Country("ES", 'Spain'),
      Country("LK", 'Sri Lanka'),
      Country("SD", 'Sudan'),
      Country("SR", 'Suriname'),
      Country("SJ", 'Svalbard and Jan Mayen'),
      Country("SZ", 'Swaziland'),
      Country("SE", 'Sweden'),
      Country("CH", 'Switzerland'),
      Country("SY", 'Syrian Arab Republic'),
      Country("TW", 'Taiwan'),
      Country("TJ", 'Tajikistan'),
      Country("TZ", 'Tanzania'),
      Country("TH", 'Thailand'),
      Country("TL", 'Timor-Leste'),
      Country("TG", 'Togo'),
      Country("TT", 'Trinidad and Tobago'),
      Country("TN", 'Tunisia'),
      Country("TR", 'Turkey'),
      Country("TM", 'Turkmenistan'),
      Country("AE", 'UAE'),
      Country("UG", 'Uganda'),
      Country("GB", 'United Kingdom'),
      Country("UA", 'Ukraine'),
      Country("US", 'USA'),
      Country("UY", 'Uruguay'),
      Country("UZ", 'Uzbekistan'),
      Country("VU", 'Vanuatu'),
      Country("VE", 'Venezuela'),
      Country("VN", 'Vietnam'),
      Country("EH", 'Western Sahara'),
      Country("YE", 'Yemen'),
      Country("ZM", 'Zambia'),
      Country("ZW", 'Zimbabwe'),
    ];
  }
}